# Generated by Django 3.0.7 on 2020-06-23 04:02

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=88, editable=False, populate_from='farm', unique=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fruit:Apple', 'Fruit:Apple'), ('Fruit:Mango', 'Fruit:Mango'), ('Fruit:Orange', 'Fruit:Orange'), ('Fruit:Cocumber', 'Fruit:Cocumber'), ('Vegetable:LadyFinger', 'Vegetable:LadyFinger'), ('Vegetable:Tomato', 'Vegetable:Tomato'), ('Vegetable:Patato', 'Vegetable:Patato'), ('Grain', 'Grain'), ('Cotton', 'Cotton'), ('Raw Material', 'Raw Material'), ('Spices', 'Spices')], max_length=20),
        ),
    ]
