# Generated by Django 3.0.7 on 2020-06-25 07:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200623_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=12, editable=False, populate_from='farm', unique=True),
        ),
    ]
