# Generated by Django 3.0.7 on 2020-06-25 11:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200625_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=9, editable=False, populate_from='farm', unique=True),
        ),
    ]
