# Generated by Django 3.0.7 on 2020-07-05 12:18

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200630_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact_number',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='Ankit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=121233, editable=False, populate_from='village_name', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Set as Default Address'),
        ),
    ]
