# Generated by Django 3.0.7 on 2020-07-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20200706_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='delivery_time_slot',
            field=models.CharField(choices=[('Morning', 'Morning(6AM-10AM)'), ('Evening', 'Evening(4PM-8PM)')], default='Morning(6AM-10AM)', max_length=20),
            preserve_default=False,
        ),
    ]
